FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir --no-compile fastapi uvicorn

COPY backend_service.py .

EXPOSE 9000

CMD ["uvicorn", "backend_service:app", "--host", "0.0.0.0", "--port", "9000"]